remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# for header and meta tags
description: redesign focused around community-building aimed for the 65+ community

github:
  is_project_page: false